FROM bellsoft/liberica-openjdk-alpine:11.0.16
COPY ./java ./src
RUN mkdir ./out
RUN echo "directory 'out' was ceated"
RUN javac -sourcepath ./src -d out src/org/example/Main.java
CMD java -classpath ./out org/example/Main